name: Release tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: planet-code/release-tag-action@1.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-branch-format: "release\/"
          show-changelog: true
